=== ringzer0dev/lnd2020-2021/students.dtd
<!ELEMENT students (student*)>
<!ELEMENT student (name, surname, class)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT class (#PCDATA)>

=== ringzer0dev/lnd2020-2021/students.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Documento *.dtd (validación de fichero XML) -->
<!DOCTYPE students SYSTEM "students.dtd">

<!-- Elemento "students" -->
<students>
    <student>
        <name>Luis</name>
        <surname>Torres</surname>
        <class>1ºDAM-T</class>
    </student>
    <student>
        <name>Juan</name>
        <surname>Ramírez</surname>
        <class>2ºDAM-T</class>
    </student>
</students>
