=== ringzer0dev/lnd2020-2021/SecondSite/sports.dtd
<!ELEMENT sports (sport*)>
<!ELEMENT sport (name, players, time)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT players (#PCDATA)>
<!ELEMENT time (#PCDATA)>

<!ATTLIST sports event CDATA #IMPLIED>

=== ringzer0dev/lnd2020-2021/SecondSite/sports.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sports SYSTEM "sports.dtd">

<sports event="Barcelona 92">
    <sport>
        <name>Baloncesto</name>
        <players>5</players>
        <time>40</time>
    </sport>
    <sport>
        <name>FÃºtbol</name>
        <players>11</players>
        <time>90</time>
    </sport>
    <sport>
        <name>Balonmano</name>
        <players>6</players>
        <time>40</time>
    </sport>
</sports>
